            - name: run-notebook
  # You may pin to the exact commit or the version.
  # uses: yaananth/run-notebook@77470edbe56a263d46c840ae9c5a7aa35124d673
  uses: yaananth/run-notebook@v2
  with:
    # Path to notebook with extension that should be executed
    notebook: rfl.ipynb # optional, default is 
    # Path to parameters file with extension, contents should be json
    params: # optional, default is {}
    # If True, will hide inputs in notebook
    isReport: # optional
    # If True, this will pool output every 15 seconds and displays, this is useful in cases where there is long running cells and user wants to see output after going to the page, since github actions does not show streaming from the beginning, this is a hack to get around it
    poll: # optional
          
