name: Execute notebook

on:
  push:
  workflow_dispatch:  # lets you run it manually too

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # pick your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements.txt, prefer this:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Otherwise make sure papermill + your libs are installed:
          pip install papermill jupyter pandas duckdb requests

      - name: Run notebook with parameters
        uses: yaananth/run-notebook@v2
        env:
          # These envs are optional; they’re just made available to the step.
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "rfl.ipynb"   # <-- update
          #params:   "notebooks/params.json"          # <-- update (optional)
          isReport: false
          poll: true

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nb-output
          path: ${{ runner.temp }}/nb-runner
